# Generated by Django 2.1.5 on 2021-04-28 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('coin', models.CharField(choices=[('LT', 'LTC'), ('ON', 'ONE'), ('TO', 'TOMO'), ('DG', 'DOGE'), ('AD', 'ADA'), ('TR', 'TRX'), ('DT', 'DOT'), ('BU', 'BUST'), ('US', 'USDT')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('cost', models.FloatField(default=0)),
            ],
            options={
                'ordering': ('-amount',),
            },
        ),
    ]
