# Generated by Django 2.1.5 on 2021-04-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donate',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
