# Generated by Django 2.1.5 on 2021-04-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20210430_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='coin',
            field=models.CharField(choices=[('LT', 'LTC'), ('ON', 'ONE'), ('EH', 'ETH'), ('DG', 'DOGE'), ('TR', 'TRX'), ('DT', 'DOT'), (
                'BU', 'BUSD'), ('US', 'USDT'), ('QT', 'QTUM'), ('XLM', 'XLM'), ('EC', 'ETC'), ('DB', 'DGB')], max_length=2),
        ),
    ]
