# Generated by Django 2.1.5 on 2020-10-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authnz', '0002_auto_20200522_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rate_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_review',
            field=models.IntegerField(default=0),
        ),
    ]
