# Generated by Django 2.1.5 on 2019-03-16 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend_to_friend', models.BooleanField()),
                ('state', models.CharField(choices=[('FULL', 'FULL TIME'), ('PART', 'PART TIME'), ('CONTRACT', 'CONTRACT'), ('INTERN', 'INTERN'), ('FREELANCE', 'FREELANCE'), ('FREELANCE', 'FREELANCE'), ('REMOTE', 'REMOTE')], max_length=10)),
                ('work_life_balance', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('salary_benefit', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('security', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('management', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('culture', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('over_all_rate', models.FloatField()),
                ('anonymous_job', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000, null=True)),
                ('salary', models.IntegerField()),
                ('salary_type', models.CharField(choices=[('YEAR', 'PER YEAR'), ('MONTH', 'PER MONTH'), ('DAY', 'PER DAY'), ('HOUR', 'PER HOUR')], max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('current_work', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Cons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('logo', models.CharField(max_length=200, null=True)),
                ('icon', models.CharField(max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('logo', models.CharField(max_length=200, null=True)),
                ('icon', models.CharField(max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='companyreview',
            name='cons',
            field=models.ManyToManyField(to='review.Cons'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.Job'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='pros',
            field=models.ManyToManyField(to='review.Pros'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='view',
            field=models.ManyToManyField(related_name='company_review_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='vote',
            field=models.ManyToManyField(related_name='company_review_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
