# Generated by Django 2.1.5 on 2019-07-31 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0003_company_cheater'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='down_vote',
            field=models.ManyToManyField(related_name='company_review_down_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='total_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interview',
            name='down_vote',
            field=models.ManyToManyField(related_name='interview_down_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interview',
            name='total_view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='cons',
            field=models.ManyToManyField(blank=True, to='review.Cons'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='pros',
            field=models.ManyToManyField(blank=True, to='review.Pros'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='cons',
            field=models.ManyToManyField(blank=True, to='review.Cons'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='pros',
            field=models.ManyToManyField(blank=True, to='review.Pros'),
        ),
    ]
