# Generated by Django 2.1.5 on 2020-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_interviewcomment_reviewcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='interviewcomment',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]