# Generated by Django 2.1.5 on 2020-09-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20200612_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='reply',
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='reply_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='reply',
            field=models.CharField(blank=True, max_length=40000, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='reply_created',
            field=models.DateTimeField(null=True),
        ),
    ]
