# Generated by Django 2.1.5 on 2021-06-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20210528_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewcomment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
