# Generated by Django 2.1.5 on 2019-01-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegerConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Config name')),
                ('value', models.IntegerField(verbose_name='Config value')),
                ('description', models.CharField(max_length=200, verbose_name='Config description')),
            ],
        ),
    ]
