# Generated by Django 2.1.5 on 2019-03-16 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('logo', models.CharField(max_length=200, null=True)),
                ('icon', models.CharField(max_length=50, null=True)),
                ('supported', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('supported', models.BooleanField(default=False)),
                ('show_name', models.CharField(max_length=100)),
                ('city_slug', models.CharField(db_index=True, max_length=50, unique=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=3000, null=True)),
                ('logo', models.CharField(max_length=200, null=True)),
                ('cover', models.CharField(max_length=200, null=True)),
                ('founded', models.DateField(null=True)),
                ('company_slug', models.SlugField(max_length=255, unique=True)),
                ('size', models.CharField(choices=[('VS', '1-10'), ('S', '11-50'), ('M', '51-200'), ('L', '201-500'), ('VL', '501-1000'), ('UL', 'More than 1000')], max_length=2)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('tell', models.CharField(blank=True, max_length=14)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('working_hours_start', models.TimeField(null=True)),
                ('working_hours_stop', models.TimeField(null=True)),
                ('work_life_balance', models.FloatField(default=0)),
                ('salary_benefit', models.FloatField(default=0)),
                ('security', models.FloatField(default=0)),
                ('management', models.IntegerField(default=0)),
                ('culture', models.FloatField(default=0)),
                ('over_all_rate', models.FloatField(default=0)),
                ('salary_avg', models.FloatField(default=0)),
                ('salary_max', models.FloatField(default=0)),
                ('salary_min', models.FloatField(default=0)),
                ('recommend_to_friend', models.IntegerField(default=0)),
                ('total_review', models.IntegerField(default=0)),
                ('benefit', models.ManyToManyField(blank=True, to='company.Benefit')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.City')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('industry_slug', models.CharField(db_index=True, max_length=100, unique=True)),
                ('logo', models.CharField(max_length=200, null=True)),
                ('icon', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=2000)),
                ('supported', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('supported', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Industry'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='view',
            field=models.ManyToManyField(related_name='company_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Province'),
        ),
    ]
