# Generated by Django 2.1.5 on 2019-05-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190408_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_cheater',
            field=models.BooleanField(default=False),
        ),
    ]
