# Generated by Django 2.1.5 on 2019-05-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_cheater'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_interview',
            field=models.IntegerField(default=0),
        ),
    ]
