# Generated by Django 2.1.5 on 2019-05-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_total_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='has_panel_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_big_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_famous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='founded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
