# Generated by Django 2.1.5 on 2019-10-09 08:17

import django.contrib.gis.geos.point
from django.db import migrations
import location_field.models.spatial


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_down_vote_total_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='company',
            name='longitude',
        ),
        migrations.AddField(
            model_name='company',
            name='location_point',
            field=location_field.models.spatial.LocationField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), null=True, srid=4326),
        ),
    ]
