# Generated by Django 2.1.5 on 2020-10-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_generated',
            field=models.BooleanField(default=False),
        ),
    ]
