# Generated by Django 2.1.5 on 2019-03-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('job_slug', models.CharField(db_index=True, max_length=50, unique=True)),
                ('cover', models.CharField(max_length=200, null=True)),
                ('icon', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
